config/routes.rb
Rails.application.routes.draw do
	root 'root#top'
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord

	validates :title,presence: true
	validates :body,presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def new
		@post = Post.new

		@posts = Post.all

	end
	def create
	    # ストロングパラメーターを使用
	     post = Post.new(post_params)
	    # DBへ保存する
	     if post.save
	    # トップ画面へリダイレクト

	    redirect_to post_path(post.id)
	    flash[:notice] = "Book was successfully created."
	end


	end

	def edit
	    @post = Post.find(params[:id])
	end
	def show
		@post = Post.find(params[:id])
	end

	def update
	    post = Post.find(params[:id])
	    if 
	    post.update(post_params)
	    redirect_to post_path(post.id)
	    flash[:notice] = "Book was successfully update."
	end

	end

	 def destroy
        post = Post.find(params[:id])
        if
        post.destroy
        redirect_to new_post_path
        flash[:notice] = "Book was successfully destroyed."
    end
    end




  private
	    def post_params
	        params.require(:post).permit(:title, :body)
	    end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
	def top
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KADAI</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>編集画面</h1>
<%= form_for(@post) do |f| %>
    <h4>タイトル</h4>
    <%= f.text_field :title %>
    <h4>本文</h4>
    <%= f.text_area :body %>
    <%= f.submit '保存' %> 
<% end %>
<%= link_to "戻る", '/posts/new' %>

app/views/posts/index.html.erb
<%= @posts %>

app/views/posts/new.html.erb
<%= flash[:notice]%>
<h1>投稿一覧</h1>
<table>
	<tr><td>タイトル</td>
	<td>本分</td></tr>
	<% @posts.each do |post| %>
    	<tr>
    		
    		<td><%= post.title %></td>
    		
    		<td><%= post.body %></td>
    		<td><%=link_to '表示', post_path(post.id) %></td>
    		<td><%= link_to "編集", edit_post_path(post.id) %></td>
    		<td><%= link_to "削除", post_path(post.id), method: :delete, "data-confirm" => "本当に削除しますか？" %></td>
		</tr>
 	<% end %>
</table>


<h1>新規投稿</h1>
<!-- form_for部分 -->


<%= form_for(@post) do |f| %>
 
    <h4>タイトル</h4>
    <%= f.text_field :title %>
 
    <h4>本文</h4>
    <%= f.text_area :body %>
 
    <%= f.submit '投稿' %>
 
<% end %>

app/views/posts/show.html.erb
<%= flash[:notice]%>
<h1>タイトル</h1>
<%= @post.title %>
<h1>本文</h1>
<%= @post.body %>
<%= link_to "戻る", '/posts/new' %>
<%= link_to "編集", edit_post_path(@post.id) %> 
<%= link_to "削除", post_path(@post.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>

app/views/root/top.html.erb
<h1>ようこそ <strong>Bookers</strong>  へ！</h1>
<p><strong>Bookers</strong>  では、さまざまな書籍に関するあなたの意見や</p><p>印象を共有し交換することができます</p>
<p><%= link_to 'start', new_post_path %></p>    	
  </body>
</html>